// <auto-generated />
using System;
using IntegrationTest.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntegrationTest.Api.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20190611200431_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntegrationTest.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<Guid?>("PositionId");

                    b.Property<Guid?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("IntegrationTest.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("746049a0-99f9-41c4-81d5-71fdecce7120"),
                            Name = "Portero"
                        },
                        new
                        {
                            Id = new Guid("c264d326-47be-470f-9c8e-c9572fbcb8fa"),
                            Name = "Defensa"
                        },
                        new
                        {
                            Id = new Guid("6ff0d80e-face-4959-b7a0-cb9b0c43275b"),
                            Name = "Centrocampista"
                        },
                        new
                        {
                            Id = new Guid("8dcefb32-2d89-4be1-885b-f020052836ac"),
                            Name = "Delantero"
                        });
                });

            modelBuilder.Entity("IntegrationTest.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("IntegrationTest.Entities.Player", b =>
                {
                    b.HasOne("IntegrationTest.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.HasOne("IntegrationTest.Entities.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
