// <auto-generated />
using System;
using IntegrationTest.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntegrationTest.Api.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20200116180228_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntegrationTest.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d4b810-8c35-4692-ac8e-f4082dcba41a"),
                            Name = "Diego Mariño"
                        },
                        new
                        {
                            Id = new Guid("779ed204-64b6-472b-8fd3-0b726cab904f"),
                            Name = "Manu García"
                        });
                });

            modelBuilder.Entity("IntegrationTest.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68bd77b6-4528-4db3-abf2-a3a4370c5e1b"),
                            Name = "Real Sporting de Gijón"
                        },
                        new
                        {
                            Id = new Guid("a5a855b0-d575-42da-8466-cb10b9324ff0"),
                            Name = "Real Betis"
                        },
                        new
                        {
                            Id = new Guid("a726f480-862c-4b58-a4eb-3f4f6cde6926"),
                            Name = "UP Langreo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
